sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tejakummarikuntla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tejakummarikuntla/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-347153497330"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: "$SECRET_ACCESS_KEY"